apiVersion: v1
kind: Service
metadata:
  name: flashcards-service
  namespace: flashcards
spec:
  selector:
    app: flashcards-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashcards-app
  namespace: flashcards
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flashcards-app
  template:
    metadata:
      labels:
        app: flashcards-app
    spec:
      containers:
        - name: flashcards-app
          image: mateycardula18/flashcards:v1.0.4
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres.flashcards:5432/flashcards"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
          ports:
            - containerPort: 8080