apiVersion: v1
kind: PersistentVolume
metadata:
  name: flashcards-pv
  namespace: flashcards
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/postgres"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flashcards-pvc
  namespace: flashcards
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

