name: Build and Push Docker Image

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Extract current version
        id: get_version
        run: |
          if [ -f VERSION ]; then
            CURRENT_VERSION=$(cat VERSION)
          else
            CURRENT_VERSION="v1.0.0"
          fi
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Increment patch version
        id: increment_version
        run: |
          OLD_VERSION=${{ env.current_version }}
          IFS='.' read -r -a version_parts <<< "${OLD_VERSION//v/}"
          PATCH=$((version_parts[2] + 1))
          NEW_VERSION="v${version_parts[0]}.${version_parts[1]}.$PATCH"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "$NEW_VERSION" > VERSION
          git add VERSION
          git commit -m "Bump version to $NEW_VERSION"
          git tag $NEW_VERSION
          git push origin main --tags

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ env.new_version }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ env.new_version }} ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ env.new_version }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
